### ISSUE TITLE
Unifi Protect Setup - Page Not Found / Latest Protect 4.0.21

### ISSUE THREAD

**Issue by dciancu** [dciancu/unifi-protect-unvr-docker-arm64#1]
There is an issue with the latest version of Unifi Protect 3.0.26, in the console it says Setup, but when clicked it redirects to a Page Not Found (`/protect/setup`).
Checking further, seems to be a user permission issue, despite the admin role of the user.
As always, Unifi `.0` versions are not very stable and have issues, which is why I recommended using the `stable` tag on this image.

The `stable` version using Protect 2.9.42 works without issues.

Linked issue: https://community.ui.com/questions/Protect-not-opening-on-UDR/6632372e-e02d-4622-95ba-08567be0a535

![f434a5d4-0e06-4e27-bdd1-4c8e2c5e237f](https://github.com/dciancu/unifi-protect-unvr-docker-arm64/assets/7402536/ee6dd09c-ec4f-4c60-ba30-ae50c81c6d8f)
![d48c6e39-9c14-4fce-9345-5e07203034fc](https://github.com/dciancu/unifi-protect-unvr-docker-arm64/assets/7402536/dd73c151-770e-4576-a8ba-aa05f76f6adc)
![abb7aa47-1307-48a0-8f4a-185b61e4c269](https://github.com/dciancu/unifi-protect-unvr-docker-arm64/assets/7402536/d8385f06-df9c-4135-bdb2-c39a86b91a43)

**Comment by dciancu** [comment]
Still the same in the latest version `4.0.21`.

![Screenshot 2024-06-01 at 00 56 08](https://github.com/dciancu/unifi-protect-unvr-docker-arm64/assets/7402536/89e7d015-f12b-47b2-badd-44b859ac496f)

**Comment by InfoX1337** [comment]
@dciancu Daniel, I've finally found the fix, join the early adopters club on the ubiquiti website (https://account.ui.com/profile), so that you are enrolled into the Early Access programme, then update the protect app to version 4.0.31. After the update it works like a charm. 
If you know how to update the Unifi OS version, please LMK. Im super interested in learning how to do that kind of stuff with UniFi software

**Comment by dciancu** [comment]
Hi, thank you for the tip, glad that this will be solved in a future release of Protect. Anyhow, I still think `.0` versions are not very stable, which is the same experience I had with UniFi Network.

Unifi OS can not be updated inside the container image, because the updater downloads a firmware which it wants to flash to a non existing flash memory. Thus the way to update Unifi OS is to build the image, see the README for more info. If you can find the URL of the Unifi OS in Early Access program, then you can use `FW_URL` env var to build the image with that firmware.

**Comment by InfoX1337** [comment]
> Hi, thank you for the tip, glad that this will be solved in a future release of Protect. Anyhow, I still think `.0` versions are not very stable, which is the same experience I had with UniFi Network.
> 
> Unifi OS can not be updated inside the container image, because the updater downloads a firmware which it wants to flash to a non existing flash memory. Thus the way to update Unifi OS is to build the image, see the README for more info. If you can find the URL of the Unifi OS in Early Access program, then you can use `FW_URL` env var to build the image with that firmware.
> 
> I have set up auto-builds for this image, and when a new Unifi OS and/or Protect is released, the images will be rebuilt automatically.

Thanks, didn't notice the build script. Will try it out, Thanks!

**Comment by dciancu** [comment]
@InfoX1337 
Just realised FW_URL env var was not working as it was not being passed as build-argument to the firmware dockerfile.
I have just fixed that (b1d4652).
Let us know if UnifiOS firmware is also available in Early Access program.

**Comment by InfoX1337** [comment]
@dciancu Will let you know soon, didn't get around to trying to build it myself yet.

**Comment by dciancu** [comment]
@InfoX1337 If you encounter any problems building, please let me know.
Basically you just need to run `build.sh` script.
With a custom FW_URL that would be `FW_URL='https://unifi.com/location-of-firmware' ./build.sh`.

**Comment by dciancu** [comment]
The images have just been rebuilt, and this issue seems to be fixed now in the latest version of Protect `4.0.33` (`edge` tag).

**Comment by xorinzor** [comment]
It took me 1,5 weeks of debugging my network connection because my mobile app wouldn't connect only to find this by sheer accident..
`edge` should be turned into `stable`, or an addition in the readme would be appreciated.

Still very happy with your work though @dciancu

**Comment by dciancu** [comment]
@xorinzor I have just updated the readme to recommend usage with a Protect specific version tag.
