### ISSUE TITLE
Can't update console beyond 4.0.6

### ISSUE THREAD

**Issue by hendymen** [dciancu/unifi-protect-unvr-docker-arm64#11]
Can't update console beyond 4.0.6, it crashes when i try so;

![image](https://github.com/user-attachments/assets/15613b6f-e9ea-4aac-9c0a-6ef0850dd25c)

i've enabled remote access and RC/EA;

![image](https://github.com/user-attachments/assets/69bf3a9b-31ec-478b-88ce-00de3e8c3be5)

I need the newest firmware to be able to run protect beyond 4.0.33 (RC/EA) because of an issue with the 4.0.33 and unifi proxy.

**Comment by xorinzor** [comment]
You shouldn't try to update this inside a docker container, as the next time the container updates all changes will be reverted if they're not included in the container itself.

A container is not a VM, whereas changes in a VM persist, a container should be used as-is.

**Comment by dciancu** [comment]
@xorinzor answered this very good.
