### ISSUE TITLE
Would it work on Debian 12 Bookworm?

### ISSUE THREAD

**Issue by linkstat** [dciancu/unifi-protect-unvr-docker-arm64#3]
Hi, I wanted to ask a question.
Would it work on Debian 12 Bookworm?

I bought a Raspberry Pi 5, but Debian 11 Bullseye is not supported on this hardware; I know that (theoretically at least), docker should work on any version of any linux distribution, but at least with the markdegroot/unifi-protect-arm64 image I have never been able to get it working on any other host system than Debian 11.

Regards!

**Comment by dciancu** [comment]
Hi, it works on Debian 12, both as docker host for the container and to build the image manually if you wish so. I am unsing it on a Deb 12 system.
Please read the README for making systemd work inside the container (you must add a boot parameter to the host system).
