### ISSUE TITLE
Could you consider fork unifi-cam-proxy and fix it?

### ISSUE THREAD

**Issue by Buster14** [dciancu/unifi-protect-unvr-docker-arm64#5]
https://github.com/keshavdv/unifi-cam-proxy

Sorry if its a bit out of topic, seems like you're the most capable since you're also porting unifi protect
If it works it would be awesome. The Hikvision incompatibility is a show stopper for me.

**Comment by dciancu** [comment]
Hi,

Thanks for bringing this to my attention, it is indeed and interesting project, but I think it is no longer necessary as Protect now has ONVIF support (albeit still in beta mode) and external cameras are now supported by UniFi directly.
The latest commit I have just made (260b1e0f41630ac0a014164d535f56adaf68de43) fixes the ONVIF adoption.

All the best,
Daniel

**Comment by dciancu** [comment]
I would also like to point to a project which aims at making any camera ONVIF compatible: https://github.com/daniela-hase/onvif-server
Also check this fork: https://github.com/p10tyr/rtsp-to-onvif
