### ISSUE TITLE
Failed to start Unifi Core

### ISSUE THREAD

**Issue by belangerpascal** [dciancu/unifi-protect-unvr-docker-arm64#6]
Hi! Awesome work.

I just did a fresh deploy with either stable or edge and I get the following error;

Jun 26 11:30:59 UNVR systemd[1]: Starting UniFi Core...
Jun 26 11:30:59 UNVR sudo[18304]:     root : PWD=/usr/share/unifi-core/app ; USER=postgres ; COMMAND=/usr/bin/createuser unifi-core -p 5432 -d
Jun 26 11:30:59 UNVR sudo[18304]: pam_unix(sudo:session): session opened for user postgres(uid=104) by (uid=0)
Jun 26 11:30:59 UNVR pre-start[18305]: createuser: error: creation of new role failed: ERROR:  role "unifi-core" already exists
Jun 26 11:30:59 UNVR sudo[18304]: pam_unix(sudo:session): session closed for user postgres
Jun 26 11:31:00 UNVR node[18321]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Jun 26 11:31:00 UNVR node[18321]: WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
Jun 26 11:31:01 UNVR node[18321]: Error during trace:error publish: trace.getConsoleMeta was published but has no subscribers.
Jun 26 11:31:01 UNVR node[18321]: crash uncaughtException: Invalid MAC address:
Jun 26 11:31:01 UNVR node[18321]: Error: Invalid MAC address:
Jun 26 11:31:01 UNVR node[18321]:     at file:///usr/share/unifi-core/app/service.js:4:307
Jun 26 11:31:01 UNVR node[18321]:     at Array.forEach (<anonymous>)
Jun 26 11:31:01 UNVR node[18321]:     at fC (file:///usr/share/unifi-core/app/service.js:4:4)
Jun 26 11:31:01 UNVR node[18321]:     at async file:///usr/share/unifi-core/app/service.js:4:904 Error: Invalid MAC address:
Jun 26 11:31:01 UNVR node[18321]:     at file:///usr/share/unifi-core/app/service.js:4:307
Jun 26 11:31:01 UNVR node[18321]:     at Array.forEach (<anonymous>)
Jun 26 11:31:01 UNVR node[18321]:     at fC (file:///usr/share/unifi-core/app/service.js:4:4)
Jun 26 11:31:01 UNVR node[18321]:     at async file:///usr/share/unifi-core/app/service.js:4:904

Thanks

**Comment by dciancu** [comment]
Please post your system info (hardware, distro, version) and network interfaces info.

**Comment by belangerpascal** [comment]
It's a RPI 5 running Raspberry OS Bookworm. 

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: end0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether d8:3a:dd:f6:b6:a7 brd ff:ff:ff:ff:ff:ff
3: wwan0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/none 
    inet 100.102.216.37/30 scope global wwan0
       valid_lft forever preferred_lft forever
4: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d8:3a:dd:f6:b6:a8 brd ff:ff:ff:ff:ff:ff
17: enp0s2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether f4:4d:ad:01:8c:c5 brd ff:ff:ff:ff:ff:ff
18: wgnet_TheCondo: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 192.168.7.8/32 scope global wgnet_TheCondo
       valid_lft forever preferred_lft forever
19: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:28:8a:f1:1c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
20: br-bc510e78bc10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:92:a3:c8:31 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-bc510e78bc10
       valid_lft forever preferred_lft forever
22: vethdf08c6a@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-bc510e78bc10 state UP group default 
    link/ether 8a:61:cc:0a:33:2d brd ff:ff:ff:ff:ff:ff link-netnsid 2
24: vethee26728@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether ea:da:92:29:cb:b1 brd ff:ff:ff:ff:ff:ff link-netnsid 1
26: veth51390f5@if25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether c6:37:70:41:99:16 brd ff:ff:ff:ff:ff:ff link-netnsid 0

**Comment by dciancu** [comment]
The error is: 'crash uncaughtException: Invalid MAC address'
It is due to the 'wwan0' not having a MAC address. Running Protect over wan is not recommended and a security issue. This image expects more or less the same network interfaces as UNVR, connected to lan. You may be using an lte modem and the driver does not assign a mac address to the interface. You can try to force a mac to the interface, maybe then Protect will not crash.
Anyhow, this is related to your setup and not the image itself. I do not offer support for this image due to lack of time.
All the best!
