### ISSUE TITLE
Smart Detection not working

### ISSUE THREAD

**Issue by rsys-dev** [dciancu/unifi-protect-unvr-docker-arm64#7]
Hi,

I just installed your project and love it, but I can't activate Smart Detection.
If I open my G5 Turret Ultra, a Modal shows up "Introducing Smart Detection" but the "Enable Smart Detection" Button ist disabled and on hover it shows "Please connect to the network to read terms and conditions"

Is this a known issue or did I miss anything?
I'm on Edge Version because Stable did not find my G5 for Adoption.

Manuel

**Comment by dciancu** [comment]
Hi, take a look at this forum post:
https://community.ui.com/questions/Cannot-enable-Smart-Detections/e3d50641-5c00-4607-9723-453cda557e35
Seems others have had the same issue.
Let me know if it worked after enabling remote access.
