### ISSUE TITLE
build stable 4.0.6 unifi-core bricks storage

### ISSUE THREAD

**Issue by wgrando1993** [dciancu/unifi-protect-unvr-docker-arm64#8]
Hi @dciancu;

After start image with 4.0.6 unifi-core, storage wasn`t detect.

![image](https://github.com/user-attachments/assets/938a582f-1301-4ff5-804c-838c3ba86f7a)

my docker-compose

`services:
  unifi-protect:
    image: dciancu/unifi-protect-unvr-docker-arm64:stable
    tty: true
    hostname: UNVR
    extra_hosts:
      - "UNVR:127.0.1.1"
    container_name: unifi-protect
    stop_grace_period: 2m
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /mnt/storage/srv:/srv
      - /mnt/storage/data:/data
      - /mnt/storage/persistent:/persistent
    environment:
      - container=docker
      - STORAGE_DISK=/dev/sda1
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    cap_add:
      - dac_read_search
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
      - /var/run/lock
    privileged: true
    network_mode: host`

and my "df -h" host machine:

![image](https://github.com/user-attachments/assets/4f63d400-2601-4302-8d4c-c21dd9d86e19)

and df -h on container:
![image](https://github.com/user-attachments/assets/1b9d431b-9cbe-4fe6-bc1c-d7bed290970e)

Disk was appears to be ok, but no dettect on protect or unifi-core.

**Comment by wgrando1993** [comment]
Curiosity, in my other unvr (a real unvr) seems different df -h result, using a raid /dev/md3:

![image](https://github.com/user-attachments/assets/6782caf6-7126-4c9a-958d-05aaeba5399a)

**Comment by lude** [comment]
Confirming I can see the same issue. Nothing has changed about my storage configuration itself.

**Comment by dciancu** [comment]
Hi,

Please check the latests builds, this has been resolved thanks to @Howaner contribution.

@wgrando1993 If you own a real UNVR, would appreciate it if you could check from time to time the `ustorage` utility and its output, I have added a `unvr_log.sh` script to make this easier.
I personally do not own a real UNVR only UDM Pro and `ustorage` utility output is different.
Many thanks.
